#!/usr/bin/env node

const { rl, randomId } = require("./bootstrap");

function reverseString(str) {
  return str.split("").reverse().join("");
}

class Route {
  constructor(input) {
    this.originalInput = input;
    this.input = this.processInput();
  }

  processInput = () => {
    let parsedInput = {};

    this.lastInput = null;

    try {
      parsedInput = JSON.parse(this.originalInput);

      this.lastInput = parsedInput;

      return parsedInput;
    } catch (e) {
      return this.originalInput;
    }
  };

  generate = () => {
    const routeId = process.argv[2] || randomId();
    const reverseId = reverseString(routeId);

    const routeObject = {
      id: routeId,
      reverseId,
    };

    if (this.lastInput !== null) {
      if (this.lastInput.length > 0) {
        this.lastInput.push(routeObject);

        return this.lastInput;
      }
    }

    return [routeObject];
  };

  write = () => {
    console.log(JSON.stringify(this.generate()));
  };
}

rl.on("line", (input) => {
  const route = new Route(input);

  route.write();
});
